---
openapi: 3.0.2
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: ok
    put:
      responses:
        200:
          description: ddd
